# Generated by Django 3.0.8 on 2020-07-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_author', models.CharField(max_length=100)),
                ('blog_date', models.DateField()),
                ('blog_description', models.TextField()),
                ('blog_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
