# Generated by Django 3.0.8 on 2020-07-23 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('my_summary', models.CharField(max_length=200)),
                ('resume', models.FileField(upload_to='resume/')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('degree', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('profile', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.CharField(max_length=150)),
                ('paper_abstract', models.TextField()),
                ('paper_published_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceResponsibilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Experience')),
            ],
        ),
        migrations.CreateModel(
            name='EducationResponsibilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Education')),
            ],
        ),
    ]
