# Generated by Django 3.0.8 on 2020-07-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_achievement_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='year',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
