# Generated by Django 3.0.8 on 2020-07-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200727_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='order_in',
            field=models.IntegerField(null=True),
        ),
    ]
