# Generated by Django 3.0.8 on 2020-07-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_achievement_order_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='order_in',
            field=models.IntegerField(unique=True),
        ),
    ]
